### ISSUE TITLE
Inconsistent script banner dimensions causing issues in grid layouts

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#395]
Example: https://www.gmodstore.com/help/tickets/create/addon

Fix:

```css
.item-listing__top {
    height: 120px;
    display: table;
    width: 100%;
}
.item-listing__top > div {
    position: relative;
    display: table-cell;
    vertical-align: middle;
    overflow: hidden;
    text-align: center;
}
.item-listing__top__img {
    max-height: 120px;
    max-width: 100%;
    width: auto;
}
.item-listing__top > div > .item-listing__background {
    position: absolute;
    width: calc(100% + 10px);
    height: calc(100% + 10px);
    background-size: cover;
    background-position: center center;
    -webkit-filter: blur(5px);
    filter: blur(5px);
    content: "";
    left: -5px;
    top: -5px;
    z-index: -1;
}
```
