### ISSUE TITLE
Addon background size changes

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#454]
Currently, the addon background size is affected by the page's scrollbar, a fix for this is simply:

```css
.addon__background {
    background-size: 1920px 670px;
}
```

This however replaces the already present `background-size: cover`, but I think this is actually a good thing. How is A (cover) better than B (1920px 670px)?

**A**
![](http://i.venner.io/2018-11-01_23-14-06.jpg)

**B**
![](http://i.venner.io/2018-11-01_23-14-33.jpg)
